format = '''$username$directory$git_branch$git_status$package$nodejs$character'''

[username]
format = '[Î”](#e25d23 bold) [$user]($style) '
disabled = false
show_always = true
style_root = 'red bold'
style_user = 'white bold'

[directory]
format = '[em](#e25d23) $read_only[$path](#D1D1D1) '
read_only = 'ğŸ”’ '
home_symbol = 'ğŸ '
truncation_length = 3
use_os_path_sep = true
truncation_symbol = 'ğŸ“/'

[git_branch]
format = '[no](#e25d23) [$symbol $branch](#D1D1D1) '
symbol = 'î‚ '

[git_status]
format     = '$all_status$ahead_behind'
stashed = 'â­• '
up_to_date = '' #âœ…
conflicted = 'â›” '
ahead = 'â¬†ï¸Ã—[${count}](#D1D1D1) '
behind = 'â¬‡ï¸Ã—[${count}](#D1D1D1) '
staged = 'ğŸ“¦Ã—[${count}](#D1D1D1) '
renamed = 'ğŸ“›Ã—[${count}](#D1D1D1) '
deleted = 'âŒÃ—[${count}](#D1D1D1) '
modified = 'ğŸ“Ã—[${count}](#D1D1D1) '
untracked = 'â“Ã—[${count}](#D1D1D1) '
diverged = 'âš ï¸ ğŸ…°ï¸Ã—[${ahead_count}](#D1D1D1) ğŸ…±ï¸Ã—[${behind_count}](#D1D1D1) '

[nodejs]
format = '[via](#e25d23) [$symbol$version](#D1D1D1) '
symbol= 'ğŸ¤– '
version_format = 'v${raw}'

[python]
format = '[$symbol$version]($style) '
style = 'bold green'

[package]
format = '[Ã©](#e25d23) [$symbol$version](#D1D1D1) '
symbol= 'ğŸ“¦ '

[character]
success_symbol = '[â¯](bold blue)'
error_symbol = '[â¯](bold red)'

[battery]
full_symbol = 'ğŸ”‹'
charging_symbol = 'ğŸ”Œ'
discharging_symbol = 'âš¡'

[[battery.display]]
threshold = 30
style = 'red'


[cmd_duration]
min_time = 10_000
format = ' took [$duration]($style)'
